#!/usr/bin/env node
/**
 * build-law-toc.mjs — regenerates the Table of Contents on law-polling.html
 * from the entry anchors themselves. Re-run after adding or renaming any LP
 * entry:  node tools/build-law-toc.mjs
 *
 * Markup and design are the v20.5.5 component (commit b0f5cb4): collapsible
 * .law-toc with tier headers, count pills, and a dense auto-fill grid of
 * LP-number links. Each link additionally carries data-status / data-pillar
 * so the page's filter chips can synchronize the ToC with the entry list.
 *
 * Writes between the LAW-TOC:BEGIN / LAW-TOC:END markers; the first run
 * inserts the marker block after the filter-count line.
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const path = join(dirname(fileURLToPath(import.meta.url)), '..', 'law-polling.html');
let html = readFileSync(path, 'utf8');

const SECTIONS = [
  ['charter-amendments', 'Charter Amendments'],
  ['federal-laws', 'Federal Laws'],
  ['regulatory-petitions', 'Regulatory Petitions'],
];

const entryRe = /<article class="law-entry([^"]*)" id="(lp-[\w-]+)">[\s\S]*?class="lp-self">(LP-[\d.]+)<\/a><\/div>\s*<h3 class="law-title">([\s\S]*?)<\/h3>[\s\S]*?class="status-badge (status-[a-z]+)"/g;
const all = [...html.matchAll(entryRe)].map((m) => ({
  pillar: /\bpillar\b/.test(m[1]) ? '1' : '0',
  id: m[2],
  num: m[3],
  title: m[4].trim(),
  status: m[5],
  pos: m.index,
}));
if (!all.length) throw new Error('no entries matched');

const totalArticles = (html.match(/<article class="law-entry/g) || []).length;
if (all.length !== totalArticles) throw new Error(`extraction mismatch: ${all.length} parsed vs ${totalArticles} articles`);

const bounds = SECTIONS.map(([id]) => html.indexOf(`id="${id}"`));
const grouped = SECTIONS.map(([id, name], i) => ({
  id,
  name,
  entries: all.filter((e) => e.pos > bounds[i] && (i === SECTIONS.length - 1 || e.pos < bounds[i + 1])),
}));
const total = grouped.reduce((n, g) => n + g.entries.length, 0);
if (total !== all.length) throw new Error(`section grouping lost entries: ${total} vs ${all.length}`);

const link = (e) =>
  `        <a href="#${e.id}" class="toc-link" data-status="${e.status}" data-pillar="${e.pillar}"><span class="toc-num">${e.num}</span> <span class="toc-txt">${e.title}</span></a>`;

const toc = `<!-- LAW-TOC:BEGIN (generated by tools/build-law-toc.mjs — do not edit by hand) -->
<div class="law-toc" id="lawToc">
  <button class="toc-toggle" id="tocToggle" aria-expanded="false" aria-controls="tocBody">
    <span><span class="toc-toggle-label">Table of Contents</span><span class="toc-toggle-hint">${total} entries &middot; Charter &middot; Federal &middot; Regulatory</span></span>
    <span class="toc-chevron" aria-hidden="true"><i class="fas fa-chevron-down"></i></span>
  </button>
  <div class="toc-body" id="tocBody">
${grouped.map((g) => `      <div class="toc-tier">
        <a href="#${g.id}" class="toc-tier-head">${g.name} <span class="toc-count">${g.entries.length}</span></a>
        <div class="toc-grid">
${g.entries.map(link).join('\n')}
        </div>
      </div>`).join('\n')}
  </div>
</div>
<!-- LAW-TOC:END -->`;

const markerRe = /<!-- LAW-TOC:BEGIN[\s\S]*?<!-- LAW-TOC:END -->/;
if (markerRe.test(html)) {
  html = html.replace(markerRe, toc);
} else {
  const anchor = /(<p class="law-filter-count" data-law-count>[^<]*<\/p>)/;
  if (!anchor.test(html)) throw new Error('filter-count anchor not found');
  html = html.replace(anchor, `$1\n\n${toc}`);
}

writeFileSync(path, html);
console.log(`law-toc: ${total} entries indexed (${grouped.map((g) => `${g.name}: ${g.entries.length}`).join(' · ')})`);
